server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: []

logging:
  level: INFO
  discardingThreshold: 0
  appenders:
    - type: console
